
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AiAssistant': typeof import("../../app/components/Ai/Assistant.vue")['default']
  'AppSettings': typeof import("../../app/components/AppSettings.vue")['default']
  'CompanyBusinessTable': typeof import("../../app/components/Company/BusinessTable.vue")['default']
  'CompanyCreateBusiness': typeof import("../../app/components/Company/CreateBusiness.vue")['default']
  'CompanyViewBusiness': typeof import("../../app/components/Company/ViewBusiness.vue")['default']
  'CustomerCreateCustomer': typeof import("../../app/components/Customer/CreateCustomer.vue")['default']
  'CustomerSupportChatSheet': typeof import("../../app/components/Customer/SupportChatSheet.vue")['default']
  'CustomerUserTable': typeof import("../../app/components/Customer/UserTable.vue")['default']
  'CustomerViewCustomer': typeof import("../../app/components/Customer/ViewCustomer.vue")['default']
  'DarkToggle': typeof import("../../app/components/DarkToggle.vue")['default']
  'FICreateFinancialInstitution': typeof import("../../app/components/FI/CreateFinancialInstitution.vue")['default']
  'FIFinancialInstitutionTable': typeof import("../../app/components/FI/FinancialInstitutionTable.vue")['default']
  'PasswordInput': typeof import("../../app/components/PasswordInput.vue")['default']
  'Search': typeof import("../../app/components/Search.vue")['default']
  'ThemeCustomize': typeof import("../../app/components/ThemeCustomize.vue")['default']
  'VendorCreate': typeof import("../../app/components/Vendor/Create.vue")['default']
  'VendorTable': typeof import("../../app/components/Vendor/Table.vue")['default']
  'AuthForgotPassword': typeof import("../../app/components/auth/ForgotPassword.vue")['default']
  'AuthNewPassword': typeof import("../../app/components/auth/NewPassword.vue")['default']
  'AuthOTPForm': typeof import("../../app/components/auth/OTPForm.vue")['default']
  'AuthSignIn': typeof import("../../app/components/auth/SignIn.vue")['default']
  'BaseBreadcrumbCustom': typeof import("../../app/components/base/BreadcrumbCustom.vue")['default']
  'BaseDateRangePicker': typeof import("../../app/components/base/DateRangePicker.vue")['default']
  'DashboardTotalVisitors': typeof import("../../app/components/dashboard/TotalVisitors.vue")['default']
  'KanbanBoard': typeof import("../../app/components/kanban/KanbanBoard.vue")['default']
  'LayoutAppSidebar': typeof import("../../app/components/layout/AppSidebar.vue")['default']
  'LayoutAuth': typeof import("../../app/components/layout/Auth.vue")['default']
  'LayoutHeader': typeof import("../../app/components/layout/Header.vue")['default']
  'LayoutSidebarNavFooter': typeof import("../../app/components/layout/SidebarNavFooter.vue")['default']
  'LayoutSidebarNavGroup': typeof import("../../app/components/layout/SidebarNavGroup.vue")['default']
  'LayoutSidebarNavHeader': typeof import("../../app/components/layout/SidebarNavHeader.vue")['default']
  'LayoutSidebarNavLink': typeof import("../../app/components/layout/SidebarNavLink.vue")['default']
  'MailAccountSwitcher': typeof import("../../app/components/mail/AccountSwitcher.vue")['default']
  'MailDisplay': typeof import("../../app/components/mail/Display.vue")['default']
  'MailLayout': typeof import("../../app/components/mail/Layout.vue")['default']
  'MailList': typeof import("../../app/components/mail/List.vue")['default']
  'MailNav': typeof import("../../app/components/mail/Nav.vue")['default']
  'NavigationMenuDemoItem': typeof import("../../app/components/navigation-menu/DemoItem.vue")['default']
  'SettingsAccountForm': typeof import("../../app/components/settings/AccountForm.vue")['default']
  'SettingsAppearanceForm': typeof import("../../app/components/settings/AppearanceForm.vue")['default']
  'SettingsDisplayForm': typeof import("../../app/components/settings/DisplayForm.vue")['default']
  'SettingsLayout': typeof import("../../app/components/settings/Layout.vue")['default']
  'SettingsNotificationsForm': typeof import("../../app/components/settings/NotificationsForm.vue")['default']
  'SettingsProfileForm': typeof import("../../app/components/settings/ProfileForm.vue")['default']
  'SettingsSidebarNav': typeof import("../../app/components/settings/SidebarNav.vue")['default']
  'TasksComponentsDataTable': typeof import("../../app/components/tasks/components/DataTable.vue")['default']
  'TasksComponentsDataTableColumnHeader': typeof import("../../app/components/tasks/components/DataTableColumnHeader.vue")['default']
  'TasksComponentsDataTableFacetedFilter': typeof import("../../app/components/tasks/components/DataTableFacetedFilter.vue")['default']
  'TasksComponentsDataTablePagination': typeof import("../../app/components/tasks/components/DataTablePagination.vue")['default']
  'TasksComponentsDataTableRowActions': typeof import("../../app/components/tasks/components/DataTableRowActions.vue")['default']
  'TasksComponentsDataTableToolbar': typeof import("../../app/components/tasks/components/DataTableToolbar.vue")['default']
  'TasksComponentsDataTableViewOptions': typeof import("../../app/components/tasks/components/DataTableViewOptions.vue")['default']
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  'AspectRatio': typeof import("../../app/components/ui/aspect-ratio/index")['AspectRatio']
  'Alert': typeof import("../../app/components/ui/alert/index")['Alert']
  'AlertDescription': typeof import("../../app/components/ui/alert/index")['AlertDescription']
  'AlertTitle': typeof import("../../app/components/ui/alert/index")['AlertTitle']
  'Accordion': typeof import("../../app/components/ui/accordion/index")['Accordion']
  'AccordionContent': typeof import("../../app/components/ui/accordion/index")['AccordionContent']
  'AccordionItem': typeof import("../../app/components/ui/accordion/index")['AccordionItem']
  'AccordionTrigger': typeof import("../../app/components/ui/accordion/index")['AccordionTrigger']
  'AlertDialog': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']
  'AlertDialogAction': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']
  'AlertDialogCancel': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']
  'AlertDialogContent': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']
  'AlertDialogDescription': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']
  'AlertDialogFooter': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']
  'AlertDialogHeader': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']
  'AlertDialogTitle': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']
  'AlertDialogTrigger': typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']
  'Avatar': typeof import("../../app/components/ui/avatar/index")['Avatar']
  'AvatarFallback': typeof import("../../app/components/ui/avatar/index")['AvatarFallback']
  'AvatarImage': typeof import("../../app/components/ui/avatar/index")['AvatarImage']
  'AutoForm': typeof import("../../app/components/ui/auto-form/index")['AutoForm']
  'AutoFormField': typeof import("../../app/components/ui/auto-form/index")['AutoFormField']
  'AutoFormFieldArray': typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldArray']
  'AutoFormFieldBoolean': typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldBoolean']
  'AutoFormFieldDate': typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldDate']
  'AutoFormFieldEnum': typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldEnum']
  'AutoFormFieldFile': typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldFile']
  'AutoFormFieldInput': typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldInput']
  'AutoFormFieldNumber': typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldNumber']
  'AutoFormFieldObject': typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldObject']
  'AutoFormLabel': typeof import("../../app/components/ui/auto-form/index")['AutoFormLabel']
  'Config': typeof import("../../app/components/ui/auto-form/index")['Config']
  'ConfigItem': typeof import("../../app/components/ui/auto-form/index")['ConfigItem']
  'FieldProps': typeof import("../../app/components/ui/auto-form/index")['FieldProps']
  'Badge': typeof import("../../app/components/ui/badge/index")['Badge']
  'Breadcrumb': typeof import("../../app/components/ui/breadcrumb/index")['Breadcrumb']
  'BreadcrumbEllipsis': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']
  'BreadcrumbItem': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbItem']
  'BreadcrumbLink': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbLink']
  'BreadcrumbList': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbList']
  'BreadcrumbPage': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbPage']
  'BreadcrumbSeparator': typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']
  'Button': typeof import("../../app/components/ui/button/index")['Button']
  'ButtonGroup': typeof import("../../app/components/ui/button-group/index")['ButtonGroup']
  'ButtonGroupSeparator': typeof import("../../app/components/ui/button-group/index")['ButtonGroupSeparator']
  'ButtonGroupText': typeof import("../../app/components/ui/button-group/index")['ButtonGroupText']
  'Calendar': typeof import("../../app/components/ui/calendar/index")['Calendar']
  'CalendarCell': typeof import("../../app/components/ui/calendar/index")['CalendarCell']
  'CalendarCellTrigger': typeof import("../../app/components/ui/calendar/index")['CalendarCellTrigger']
  'CalendarGrid': typeof import("../../app/components/ui/calendar/index")['CalendarGrid']
  'CalendarGridBody': typeof import("../../app/components/ui/calendar/index")['CalendarGridBody']
  'CalendarGridHead': typeof import("../../app/components/ui/calendar/index")['CalendarGridHead']
  'CalendarGridRow': typeof import("../../app/components/ui/calendar/index")['CalendarGridRow']
  'CalendarHeadCell': typeof import("../../app/components/ui/calendar/index")['CalendarHeadCell']
  'CalendarHeader': typeof import("../../app/components/ui/calendar/index")['CalendarHeader']
  'CalendarHeading': typeof import("../../app/components/ui/calendar/index")['CalendarHeading']
  'CalendarNextButton': typeof import("../../app/components/ui/calendar/index")['CalendarNextButton']
  'CalendarPrevButton': typeof import("../../app/components/ui/calendar/index")['CalendarPrevButton']
  'Card': typeof import("../../app/components/ui/card/index")['Card']
  'CardAction': typeof import("../../app/components/ui/card/index")['CardAction']
  'CardContent': typeof import("../../app/components/ui/card/index")['CardContent']
  'CardDescription': typeof import("../../app/components/ui/card/index")['CardDescription']
  'CardFooter': typeof import("../../app/components/ui/card/index")['CardFooter']
  'CardHeader': typeof import("../../app/components/ui/card/index")['CardHeader']
  'CardTitle': typeof import("../../app/components/ui/card/index")['CardTitle']
  'Carousel': typeof import("../../app/components/ui/carousel/index")['Carousel']
  'CarouselContent': typeof import("../../app/components/ui/carousel/index")['CarouselContent']
  'CarouselItem': typeof import("../../app/components/ui/carousel/index")['CarouselItem']
  'CarouselNext': typeof import("../../app/components/ui/carousel/index")['CarouselNext']
  'CarouselPrevious': typeof import("../../app/components/ui/carousel/index")['CarouselPrevious']
  'CarouselApi': typeof import("../../app/components/ui/carousel/index")['CarouselApi']
  'AreaChart': typeof import("../../app/components/ui/chart-area/index")['AreaChart']
  'BarChart': typeof import("../../app/components/ui/chart-bar/index")['BarChart']
  'LineChart': typeof import("../../app/components/ui/chart-line/index")['LineChart']
  'Command': typeof import("../../app/components/ui/command/index")['Command']
  'CommandDialog': typeof import("../../app/components/ui/command/index")['CommandDialog']
  'CommandEmpty': typeof import("../../app/components/ui/command/index")['CommandEmpty']
  'CommandGroup': typeof import("../../app/components/ui/command/index")['CommandGroup']
  'CommandInput': typeof import("../../app/components/ui/command/index")['CommandInput']
  'CommandItem': typeof import("../../app/components/ui/command/index")['CommandItem']
  'CommandList': typeof import("../../app/components/ui/command/index")['CommandList']
  'CommandSeparator': typeof import("../../app/components/ui/command/index")['CommandSeparator']
  'CommandShortcut': typeof import("../../app/components/ui/command/index")['CommandShortcut']
  'Checkbox': typeof import("../../app/components/ui/checkbox/index")['Checkbox']
  'DonutChart': typeof import("../../app/components/ui/chart-donut/index")['DonutChart']
  'ChartCrosshair': typeof import("../../app/components/ui/chart/index")['ChartCrosshair']
  'ChartLegend': typeof import("../../app/components/ui/chart/index")['ChartLegend']
  'ChartSingleTooltip': typeof import("../../app/components/ui/chart/index")['ChartSingleTooltip']
  'ChartTooltip': typeof import("../../app/components/ui/chart/index")['ChartTooltip']
  'Collapsible': typeof import("../../app/components/ui/collapsible/index")['Collapsible']
  'CollapsibleContent': typeof import("../../app/components/ui/collapsible/index")['CollapsibleContent']
  'CollapsibleTrigger': typeof import("../../app/components/ui/collapsible/index")['CollapsibleTrigger']
  'Field': typeof import("../../app/components/ui/field/index")['Field']
  'FieldContent': typeof import("../../app/components/ui/field/index")['FieldContent']
  'FieldDescription': typeof import("../../app/components/ui/field/index")['FieldDescription']
  'FieldError': typeof import("../../app/components/ui/field/index")['FieldError']
  'FieldGroup': typeof import("../../app/components/ui/field/index")['FieldGroup']
  'FieldLabel': typeof import("../../app/components/ui/field/index")['FieldLabel']
  'FieldLegend': typeof import("../../app/components/ui/field/index")['FieldLegend']
  'FieldSeparator': typeof import("../../app/components/ui/field/index")['FieldSeparator']
  'FieldSet': typeof import("../../app/components/ui/field/index")['FieldSet']
  'FieldTitle': typeof import("../../app/components/ui/field/index")['FieldTitle']
  'Combobox': typeof import("../../app/components/ui/combobox/index")['Combobox']
  'ComboboxAnchor': typeof import("../../app/components/ui/combobox/index")['ComboboxAnchor']
  'ComboboxEmpty': typeof import("../../app/components/ui/combobox/index")['ComboboxEmpty']
  'ComboboxGroup': typeof import("../../app/components/ui/combobox/index")['ComboboxGroup']
  'ComboboxInput': typeof import("../../app/components/ui/combobox/index")['ComboboxInput']
  'ComboboxItem': typeof import("../../app/components/ui/combobox/index")['ComboboxItem']
  'ComboboxItemIndicator': typeof import("../../app/components/ui/combobox/index")['ComboboxItemIndicator']
  'ComboboxList': typeof import("../../app/components/ui/combobox/index")['ComboboxList']
  'ComboboxSeparator': typeof import("../../app/components/ui/combobox/index")['ComboboxSeparator']
  'ComboboxViewport': typeof import("../../app/components/ui/combobox/index")['ComboboxViewport']
  'ComboboxCancel': typeof import("../../app/components/ui/combobox/index")['ComboboxCancel']
  'ComboboxTrigger': typeof import("../../app/components/ui/combobox/index")['ComboboxTrigger']
  'DropdownMenu': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']
  'DropdownMenuCheckboxItem': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
  'DropdownMenuContent': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
  'DropdownMenuGroup': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
  'DropdownMenuItem': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
  'DropdownMenuLabel': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
  'DropdownMenuRadioGroup': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
  'DropdownMenuRadioItem': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
  'DropdownMenuSeparator': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
  'DropdownMenuShortcut': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
  'DropdownMenuSub': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
  'DropdownMenuSubContent': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
  'DropdownMenuSubTrigger': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
  'DropdownMenuTrigger': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
  'DropdownMenuPortal': typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
  'Empty': typeof import("../../app/components/ui/empty/index")['Empty']
  'EmptyContent': typeof import("../../app/components/ui/empty/index")['EmptyContent']
  'EmptyDescription': typeof import("../../app/components/ui/empty/index")['EmptyDescription']
  'EmptyHeader': typeof import("../../app/components/ui/empty/index")['EmptyHeader']
  'EmptyMedia': typeof import("../../app/components/ui/empty/index")['EmptyMedia']
  'EmptyTitle': typeof import("../../app/components/ui/empty/index")['EmptyTitle']
  'HoverCard': typeof import("../../app/components/ui/hover-card/index")['HoverCard']
  'HoverCardContent': typeof import("../../app/components/ui/hover-card/index")['HoverCardContent']
  'HoverCardTrigger': typeof import("../../app/components/ui/hover-card/index")['HoverCardTrigger']
  'ContextMenu': typeof import("../../app/components/ui/context-menu/index")['ContextMenu']
  'ContextMenuCheckboxItem': typeof import("../../app/components/ui/context-menu/index")['ContextMenuCheckboxItem']
  'ContextMenuContent': typeof import("../../app/components/ui/context-menu/index")['ContextMenuContent']
  'ContextMenuGroup': typeof import("../../app/components/ui/context-menu/index")['ContextMenuGroup']
  'ContextMenuItem': typeof import("../../app/components/ui/context-menu/index")['ContextMenuItem']
  'ContextMenuLabel': typeof import("../../app/components/ui/context-menu/index")['ContextMenuLabel']
  'ContextMenuRadioGroup': typeof import("../../app/components/ui/context-menu/index")['ContextMenuRadioGroup']
  'ContextMenuRadioItem': typeof import("../../app/components/ui/context-menu/index")['ContextMenuRadioItem']
  'ContextMenuSeparator': typeof import("../../app/components/ui/context-menu/index")['ContextMenuSeparator']
  'ContextMenuShortcut': typeof import("../../app/components/ui/context-menu/index")['ContextMenuShortcut']
  'ContextMenuSub': typeof import("../../app/components/ui/context-menu/index")['ContextMenuSub']
  'ContextMenuSubContent': typeof import("../../app/components/ui/context-menu/index")['ContextMenuSubContent']
  'ContextMenuSubTrigger': typeof import("../../app/components/ui/context-menu/index")['ContextMenuSubTrigger']
  'ContextMenuTrigger': typeof import("../../app/components/ui/context-menu/index")['ContextMenuTrigger']
  'Input': typeof import("../../app/components/ui/input/index")['Input']
  'InputGroup': typeof import("../../app/components/ui/input-group/index")['InputGroup']
  'InputGroupAddon': typeof import("../../app/components/ui/input-group/index")['InputGroupAddon']
  'InputGroupButton': typeof import("../../app/components/ui/input-group/index")['InputGroupButton']
  'InputGroupInput': typeof import("../../app/components/ui/input-group/index")['InputGroupInput']
  'InputGroupText': typeof import("../../app/components/ui/input-group/index")['InputGroupText']
  'InputGroupTextarea': typeof import("../../app/components/ui/input-group/index")['InputGroupTextarea']
  'InputOTP': typeof import("../../app/components/ui/input-otp/index")['InputOTP']
  'InputOTPGroup': typeof import("../../app/components/ui/input-otp/index")['InputOTPGroup']
  'InputOTPSeparator': typeof import("../../app/components/ui/input-otp/index")['InputOTPSeparator']
  'InputOTPSlot': typeof import("../../app/components/ui/input-otp/index")['InputOTPSlot']
  'Dialog': typeof import("../../app/components/ui/dialog/index")['Dialog']
  'DialogClose': typeof import("../../app/components/ui/dialog/index")['DialogClose']
  'DialogContent': typeof import("../../app/components/ui/dialog/index")['DialogContent']
  'DialogDescription': typeof import("../../app/components/ui/dialog/index")['DialogDescription']
  'DialogFooter': typeof import("../../app/components/ui/dialog/index")['DialogFooter']
  'DialogHeader': typeof import("../../app/components/ui/dialog/index")['DialogHeader']
  'DialogOverlay': typeof import("../../app/components/ui/dialog/index")['DialogOverlay']
  'DialogScrollContent': typeof import("../../app/components/ui/dialog/index")['DialogScrollContent']
  'DialogTitle': typeof import("../../app/components/ui/dialog/index")['DialogTitle']
  'DialogTrigger': typeof import("../../app/components/ui/dialog/index")['DialogTrigger']
  'Item': typeof import("../../app/components/ui/item/index")['Item']
  'ItemActions': typeof import("../../app/components/ui/item/index")['ItemActions']
  'ItemContent': typeof import("../../app/components/ui/item/index")['ItemContent']
  'ItemDescription': typeof import("../../app/components/ui/item/index")['ItemDescription']
  'ItemFooter': typeof import("../../app/components/ui/item/index")['ItemFooter']
  'ItemGroup': typeof import("../../app/components/ui/item/index")['ItemGroup']
  'ItemHeader': typeof import("../../app/components/ui/item/index")['ItemHeader']
  'ItemMedia': typeof import("../../app/components/ui/item/index")['ItemMedia']
  'ItemSeparator': typeof import("../../app/components/ui/item/index")['ItemSeparator']
  'ItemTitle': typeof import("../../app/components/ui/item/index")['ItemTitle']
  'Label': typeof import("../../app/components/ui/label/index")['Label']
  'Drawer': typeof import("../../app/components/ui/drawer/index")['Drawer']
  'DrawerClose': typeof import("../../app/components/ui/drawer/index")['DrawerClose']
  'DrawerContent': typeof import("../../app/components/ui/drawer/index")['DrawerContent']
  'DrawerDescription': typeof import("../../app/components/ui/drawer/index")['DrawerDescription']
  'DrawerFooter': typeof import("../../app/components/ui/drawer/index")['DrawerFooter']
  'DrawerHeader': typeof import("../../app/components/ui/drawer/index")['DrawerHeader']
  'DrawerOverlay': typeof import("../../app/components/ui/drawer/index")['DrawerOverlay']
  'DrawerTitle': typeof import("../../app/components/ui/drawer/index")['DrawerTitle']
  'DrawerTrigger': typeof import("../../app/components/ui/drawer/index")['DrawerTrigger']
  'Kbd': typeof import("../../app/components/ui/kbd/index")['Kbd']
  'KbdGroup': typeof import("../../app/components/ui/kbd/index")['KbdGroup']
  'FormControl': typeof import("../../app/components/ui/form/index")['FormControl']
  'FormDescription': typeof import("../../app/components/ui/form/index")['FormDescription']
  'FormItem': typeof import("../../app/components/ui/form/index")['FormItem']
  'FormLabel': typeof import("../../app/components/ui/form/index")['FormLabel']
  'FormMessage': typeof import("../../app/components/ui/form/index")['FormMessage']
  'FORMITEMINJECTIONKEY': typeof import("../../app/components/ui/form/index")['FORM_ITEM_INJECTION_KEY']
  'Form': typeof import("../../app/components/ui/form/index")['Form']
  'FormField': typeof import("../../app/components/ui/form/index")['FormField']
  'FormFieldArray': typeof import("../../app/components/ui/form/index")['FormFieldArray']
  'NativeSelect': typeof import("../../app/components/ui/native-select/index")['NativeSelect']
  'NativeSelectOptGroup': typeof import("../../app/components/ui/native-select/index")['NativeSelectOptGroup']
  'NativeSelectOption': typeof import("../../app/components/ui/native-select/index")['NativeSelectOption']
  'Menubar': typeof import("../../app/components/ui/menubar/index")['Menubar']
  'MenubarCheckboxItem': typeof import("../../app/components/ui/menubar/index")['MenubarCheckboxItem']
  'MenubarContent': typeof import("../../app/components/ui/menubar/index")['MenubarContent']
  'MenubarGroup': typeof import("../../app/components/ui/menubar/index")['MenubarGroup']
  'MenubarItem': typeof import("../../app/components/ui/menubar/index")['MenubarItem']
  'MenubarLabel': typeof import("../../app/components/ui/menubar/index")['MenubarLabel']
  'MenubarMenu': typeof import("../../app/components/ui/menubar/index")['MenubarMenu']
  'MenubarRadioGroup': typeof import("../../app/components/ui/menubar/index")['MenubarRadioGroup']
  'MenubarRadioItem': typeof import("../../app/components/ui/menubar/index")['MenubarRadioItem']
  'MenubarSeparator': typeof import("../../app/components/ui/menubar/index")['MenubarSeparator']
  'MenubarShortcut': typeof import("../../app/components/ui/menubar/index")['MenubarShortcut']
  'MenubarSub': typeof import("../../app/components/ui/menubar/index")['MenubarSub']
  'MenubarSubContent': typeof import("../../app/components/ui/menubar/index")['MenubarSubContent']
  'MenubarSubTrigger': typeof import("../../app/components/ui/menubar/index")['MenubarSubTrigger']
  'MenubarTrigger': typeof import("../../app/components/ui/menubar/index")['MenubarTrigger']
  'NavigationMenu': typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenu']
  'NavigationMenuContent': typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuContent']
  'NavigationMenuIndicator': typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuIndicator']
  'NavigationMenuItem': typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuItem']
  'NavigationMenuLink': typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuLink']
  'NavigationMenuList': typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuList']
  'NavigationMenuTrigger': typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuTrigger']
  'NavigationMenuViewport': typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuViewport']
  'NumberField': typeof import("../../app/components/ui/number-field/index")['NumberField']
  'NumberFieldContent': typeof import("../../app/components/ui/number-field/index")['NumberFieldContent']
  'NumberFieldDecrement': typeof import("../../app/components/ui/number-field/index")['NumberFieldDecrement']
  'NumberFieldIncrement': typeof import("../../app/components/ui/number-field/index")['NumberFieldIncrement']
  'NumberFieldInput': typeof import("../../app/components/ui/number-field/index")['NumberFieldInput']
  'PinInput': typeof import("../../app/components/ui/pin-input/index")['PinInput']
  'PinInputGroup': typeof import("../../app/components/ui/pin-input/index")['PinInputGroup']
  'PinInputSeparator': typeof import("../../app/components/ui/pin-input/index")['PinInputSeparator']
  'PinInputSlot': typeof import("../../app/components/ui/pin-input/index")['PinInputSlot']
  'Pagination': typeof import("../../app/components/ui/pagination/index")['Pagination']
  'PaginationContent': typeof import("../../app/components/ui/pagination/index")['PaginationContent']
  'PaginationEllipsis': typeof import("../../app/components/ui/pagination/index")['PaginationEllipsis']
  'PaginationFirst': typeof import("../../app/components/ui/pagination/index")['PaginationFirst']
  'PaginationItem': typeof import("../../app/components/ui/pagination/index")['PaginationItem']
  'PaginationLast': typeof import("../../app/components/ui/pagination/index")['PaginationLast']
  'PaginationNext': typeof import("../../app/components/ui/pagination/index")['PaginationNext']
  'PaginationPrevious': typeof import("../../app/components/ui/pagination/index")['PaginationPrevious']
  'Progress': typeof import("../../app/components/ui/progress/index")['Progress']
  'RadioGroup': typeof import("../../app/components/ui/radio-group/index")['RadioGroup']
  'RadioGroupItem': typeof import("../../app/components/ui/radio-group/index")['RadioGroupItem']
  'Popover': typeof import("../../app/components/ui/popover/index")['Popover']
  'PopoverAnchor': typeof import("../../app/components/ui/popover/index")['PopoverAnchor']
  'PopoverContent': typeof import("../../app/components/ui/popover/index")['PopoverContent']
  'PopoverTrigger': typeof import("../../app/components/ui/popover/index")['PopoverTrigger']
  'ResizableHandle': typeof import("../../app/components/ui/resizable/index")['ResizableHandle']
  'ResizablePanel': typeof import("../../app/components/ui/resizable/index")['ResizablePanel']
  'ResizablePanelGroup': typeof import("../../app/components/ui/resizable/index")['ResizablePanelGroup']
  'ScrollArea': typeof import("../../app/components/ui/scroll-area/index")['ScrollArea']
  'ScrollBar': typeof import("../../app/components/ui/scroll-area/index")['ScrollBar']
  'RangeCalendar': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendar']
  'RangeCalendarCell': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarCell']
  'RangeCalendarCellTrigger': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarCellTrigger']
  'RangeCalendarGrid': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGrid']
  'RangeCalendarGridBody': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridBody']
  'RangeCalendarGridHead': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridHead']
  'RangeCalendarGridRow': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridRow']
  'RangeCalendarHeadCell': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeadCell']
  'RangeCalendarHeader': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeader']
  'RangeCalendarHeading': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeading']
  'RangeCalendarNextButton': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarNextButton']
  'RangeCalendarPrevButton': typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarPrevButton']
  'Separator': typeof import("../../app/components/ui/separator/index")['Separator']
  'Sheet': typeof import("../../app/components/ui/sheet/index")['Sheet']
  'SheetClose': typeof import("../../app/components/ui/sheet/index")['SheetClose']
  'SheetContent': typeof import("../../app/components/ui/sheet/index")['SheetContent']
  'SheetDescription': typeof import("../../app/components/ui/sheet/index")['SheetDescription']
  'SheetFooter': typeof import("../../app/components/ui/sheet/index")['SheetFooter']
  'SheetHeader': typeof import("../../app/components/ui/sheet/index")['SheetHeader']
  'SheetTitle': typeof import("../../app/components/ui/sheet/index")['SheetTitle']
  'SheetTrigger': typeof import("../../app/components/ui/sheet/index")['SheetTrigger']
  'Toaster': typeof import("../../app/components/ui/sonner/index")['Toaster']
  'Skeleton': typeof import("../../app/components/ui/skeleton/index")['Skeleton']
  'Sidebar': typeof import("../../app/components/ui/sidebar/index")['Sidebar']
  'SidebarContent': typeof import("../../app/components/ui/sidebar/index")['SidebarContent']
  'SidebarFooter': typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']
  'SidebarGroup': typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']
  'SidebarGroupAction': typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']
  'SidebarGroupContent': typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']
  'SidebarGroupLabel': typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']
  'SidebarHeader': typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']
  'SidebarInput': typeof import("../../app/components/ui/sidebar/index")['SidebarInput']
  'SidebarInset': typeof import("../../app/components/ui/sidebar/index")['SidebarInset']
  'SidebarMenu': typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']
  'SidebarMenuAction': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']
  'SidebarMenuBadge': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']
  'SidebarMenuButton': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']
  'SidebarMenuItem': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']
  'SidebarMenuSkeleton': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']
  'SidebarMenuSub': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']
  'SidebarMenuSubButton': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']
  'SidebarMenuSubItem': typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']
  'SidebarProvider': typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']
  'SidebarRail': typeof import("../../app/components/ui/sidebar/index")['SidebarRail']
  'SidebarSeparator': typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']
  'SidebarTrigger': typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']
  'Select': typeof import("../../app/components/ui/select/index")['Select']
  'SelectContent': typeof import("../../app/components/ui/select/index")['SelectContent']
  'SelectGroup': typeof import("../../app/components/ui/select/index")['SelectGroup']
  'SelectItem': typeof import("../../app/components/ui/select/index")['SelectItem']
  'SelectItemText': typeof import("../../app/components/ui/select/index")['SelectItemText']
  'SelectLabel': typeof import("../../app/components/ui/select/index")['SelectLabel']
  'SelectScrollDownButton': typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']
  'SelectScrollUpButton': typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']
  'SelectSeparator': typeof import("../../app/components/ui/select/index")['SelectSeparator']
  'SelectTrigger': typeof import("../../app/components/ui/select/index")['SelectTrigger']
  'SelectValue': typeof import("../../app/components/ui/select/index")['SelectValue']
  'Slider': typeof import("../../app/components/ui/slider/index")['Slider']
  'Spinner': typeof import("../../app/components/ui/spinner/index")['Spinner']
  'Table': typeof import("../../app/components/ui/table/index")['Table']
  'TableBody': typeof import("../../app/components/ui/table/index")['TableBody']
  'TableCaption': typeof import("../../app/components/ui/table/index")['TableCaption']
  'TableCell': typeof import("../../app/components/ui/table/index")['TableCell']
  'TableEmpty': typeof import("../../app/components/ui/table/index")['TableEmpty']
  'TableFooter': typeof import("../../app/components/ui/table/index")['TableFooter']
  'TableHead': typeof import("../../app/components/ui/table/index")['TableHead']
  'TableHeader': typeof import("../../app/components/ui/table/index")['TableHeader']
  'TableRow': typeof import("../../app/components/ui/table/index")['TableRow']
  'Tabs': typeof import("../../app/components/ui/tabs/index")['Tabs']
  'TabsContent': typeof import("../../app/components/ui/tabs/index")['TabsContent']
  'TabsList': typeof import("../../app/components/ui/tabs/index")['TabsList']
  'TabsTrigger': typeof import("../../app/components/ui/tabs/index")['TabsTrigger']
  'Switch': typeof import("../../app/components/ui/switch/index")['Switch']
  'Stepper': typeof import("../../app/components/ui/stepper/index")['Stepper']
  'StepperDescription': typeof import("../../app/components/ui/stepper/index")['StepperDescription']
  'StepperIndicator': typeof import("../../app/components/ui/stepper/index")['StepperIndicator']
  'StepperItem': typeof import("../../app/components/ui/stepper/index")['StepperItem']
  'StepperSeparator': typeof import("../../app/components/ui/stepper/index")['StepperSeparator']
  'StepperTitle': typeof import("../../app/components/ui/stepper/index")['StepperTitle']
  'StepperTrigger': typeof import("../../app/components/ui/stepper/index")['StepperTrigger']
  'TagsInput': typeof import("../../app/components/ui/tags-input/index")['TagsInput']
  'TagsInputInput': typeof import("../../app/components/ui/tags-input/index")['TagsInputInput']
  'TagsInputItem': typeof import("../../app/components/ui/tags-input/index")['TagsInputItem']
  'TagsInputItemDelete': typeof import("../../app/components/ui/tags-input/index")['TagsInputItemDelete']
  'TagsInputItemText': typeof import("../../app/components/ui/tags-input/index")['TagsInputItemText']
  'Textarea': typeof import("../../app/components/ui/textarea/index")['Textarea']
  'ToggleGroup': typeof import("../../app/components/ui/toggle-group/index")['ToggleGroup']
  'ToggleGroupItem': typeof import("../../app/components/ui/toggle-group/index")['ToggleGroupItem']
  'Toggle': typeof import("../../app/components/ui/toggle/index")['Toggle']
  'Tooltip': typeof import("../../app/components/ui/tooltip/index")['Tooltip']
  'TooltipContent': typeof import("../../app/components/ui/tooltip/index")['TooltipContent']
  'TooltipProvider': typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']
  'TooltipTrigger': typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']
  'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyAiAssistant': LazyComponent<typeof import("../../app/components/Ai/Assistant.vue")['default']>
  'LazyAppSettings': LazyComponent<typeof import("../../app/components/AppSettings.vue")['default']>
  'LazyCompanyBusinessTable': LazyComponent<typeof import("../../app/components/Company/BusinessTable.vue")['default']>
  'LazyCompanyCreateBusiness': LazyComponent<typeof import("../../app/components/Company/CreateBusiness.vue")['default']>
  'LazyCompanyViewBusiness': LazyComponent<typeof import("../../app/components/Company/ViewBusiness.vue")['default']>
  'LazyCustomerCreateCustomer': LazyComponent<typeof import("../../app/components/Customer/CreateCustomer.vue")['default']>
  'LazyCustomerSupportChatSheet': LazyComponent<typeof import("../../app/components/Customer/SupportChatSheet.vue")['default']>
  'LazyCustomerUserTable': LazyComponent<typeof import("../../app/components/Customer/UserTable.vue")['default']>
  'LazyCustomerViewCustomer': LazyComponent<typeof import("../../app/components/Customer/ViewCustomer.vue")['default']>
  'LazyDarkToggle': LazyComponent<typeof import("../../app/components/DarkToggle.vue")['default']>
  'LazyFICreateFinancialInstitution': LazyComponent<typeof import("../../app/components/FI/CreateFinancialInstitution.vue")['default']>
  'LazyFIFinancialInstitutionTable': LazyComponent<typeof import("../../app/components/FI/FinancialInstitutionTable.vue")['default']>
  'LazyPasswordInput': LazyComponent<typeof import("../../app/components/PasswordInput.vue")['default']>
  'LazySearch': LazyComponent<typeof import("../../app/components/Search.vue")['default']>
  'LazyThemeCustomize': LazyComponent<typeof import("../../app/components/ThemeCustomize.vue")['default']>
  'LazyVendorCreate': LazyComponent<typeof import("../../app/components/Vendor/Create.vue")['default']>
  'LazyVendorTable': LazyComponent<typeof import("../../app/components/Vendor/Table.vue")['default']>
  'LazyAuthForgotPassword': LazyComponent<typeof import("../../app/components/auth/ForgotPassword.vue")['default']>
  'LazyAuthNewPassword': LazyComponent<typeof import("../../app/components/auth/NewPassword.vue")['default']>
  'LazyAuthOTPForm': LazyComponent<typeof import("../../app/components/auth/OTPForm.vue")['default']>
  'LazyAuthSignIn': LazyComponent<typeof import("../../app/components/auth/SignIn.vue")['default']>
  'LazyBaseBreadcrumbCustom': LazyComponent<typeof import("../../app/components/base/BreadcrumbCustom.vue")['default']>
  'LazyBaseDateRangePicker': LazyComponent<typeof import("../../app/components/base/DateRangePicker.vue")['default']>
  'LazyDashboardTotalVisitors': LazyComponent<typeof import("../../app/components/dashboard/TotalVisitors.vue")['default']>
  'LazyKanbanBoard': LazyComponent<typeof import("../../app/components/kanban/KanbanBoard.vue")['default']>
  'LazyLayoutAppSidebar': LazyComponent<typeof import("../../app/components/layout/AppSidebar.vue")['default']>
  'LazyLayoutAuth': LazyComponent<typeof import("../../app/components/layout/Auth.vue")['default']>
  'LazyLayoutHeader': LazyComponent<typeof import("../../app/components/layout/Header.vue")['default']>
  'LazyLayoutSidebarNavFooter': LazyComponent<typeof import("../../app/components/layout/SidebarNavFooter.vue")['default']>
  'LazyLayoutSidebarNavGroup': LazyComponent<typeof import("../../app/components/layout/SidebarNavGroup.vue")['default']>
  'LazyLayoutSidebarNavHeader': LazyComponent<typeof import("../../app/components/layout/SidebarNavHeader.vue")['default']>
  'LazyLayoutSidebarNavLink': LazyComponent<typeof import("../../app/components/layout/SidebarNavLink.vue")['default']>
  'LazyMailAccountSwitcher': LazyComponent<typeof import("../../app/components/mail/AccountSwitcher.vue")['default']>
  'LazyMailDisplay': LazyComponent<typeof import("../../app/components/mail/Display.vue")['default']>
  'LazyMailLayout': LazyComponent<typeof import("../../app/components/mail/Layout.vue")['default']>
  'LazyMailList': LazyComponent<typeof import("../../app/components/mail/List.vue")['default']>
  'LazyMailNav': LazyComponent<typeof import("../../app/components/mail/Nav.vue")['default']>
  'LazyNavigationMenuDemoItem': LazyComponent<typeof import("../../app/components/navigation-menu/DemoItem.vue")['default']>
  'LazySettingsAccountForm': LazyComponent<typeof import("../../app/components/settings/AccountForm.vue")['default']>
  'LazySettingsAppearanceForm': LazyComponent<typeof import("../../app/components/settings/AppearanceForm.vue")['default']>
  'LazySettingsDisplayForm': LazyComponent<typeof import("../../app/components/settings/DisplayForm.vue")['default']>
  'LazySettingsLayout': LazyComponent<typeof import("../../app/components/settings/Layout.vue")['default']>
  'LazySettingsNotificationsForm': LazyComponent<typeof import("../../app/components/settings/NotificationsForm.vue")['default']>
  'LazySettingsProfileForm': LazyComponent<typeof import("../../app/components/settings/ProfileForm.vue")['default']>
  'LazySettingsSidebarNav': LazyComponent<typeof import("../../app/components/settings/SidebarNav.vue")['default']>
  'LazyTasksComponentsDataTable': LazyComponent<typeof import("../../app/components/tasks/components/DataTable.vue")['default']>
  'LazyTasksComponentsDataTableColumnHeader': LazyComponent<typeof import("../../app/components/tasks/components/DataTableColumnHeader.vue")['default']>
  'LazyTasksComponentsDataTableFacetedFilter': LazyComponent<typeof import("../../app/components/tasks/components/DataTableFacetedFilter.vue")['default']>
  'LazyTasksComponentsDataTablePagination': LazyComponent<typeof import("../../app/components/tasks/components/DataTablePagination.vue")['default']>
  'LazyTasksComponentsDataTableRowActions': LazyComponent<typeof import("../../app/components/tasks/components/DataTableRowActions.vue")['default']>
  'LazyTasksComponentsDataTableToolbar': LazyComponent<typeof import("../../app/components/tasks/components/DataTableToolbar.vue")['default']>
  'LazyTasksComponentsDataTableViewOptions': LazyComponent<typeof import("../../app/components/tasks/components/DataTableViewOptions.vue")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  'LazyAspectRatio': LazyComponent<typeof import("../../app/components/ui/aspect-ratio/index")['AspectRatio']>
  'LazyAlert': LazyComponent<typeof import("../../app/components/ui/alert/index")['Alert']>
  'LazyAlertDescription': LazyComponent<typeof import("../../app/components/ui/alert/index")['AlertDescription']>
  'LazyAlertTitle': LazyComponent<typeof import("../../app/components/ui/alert/index")['AlertTitle']>
  'LazyAccordion': LazyComponent<typeof import("../../app/components/ui/accordion/index")['Accordion']>
  'LazyAccordionContent': LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionContent']>
  'LazyAccordionItem': LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionItem']>
  'LazyAccordionTrigger': LazyComponent<typeof import("../../app/components/ui/accordion/index")['AccordionTrigger']>
  'LazyAlertDialog': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialog']>
  'LazyAlertDialogAction': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogAction']>
  'LazyAlertDialogCancel': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogCancel']>
  'LazyAlertDialogContent': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogContent']>
  'LazyAlertDialogDescription': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogDescription']>
  'LazyAlertDialogFooter': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogFooter']>
  'LazyAlertDialogHeader': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogHeader']>
  'LazyAlertDialogTitle': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTitle']>
  'LazyAlertDialogTrigger': LazyComponent<typeof import("../../app/components/ui/alert-dialog/index")['AlertDialogTrigger']>
  'LazyAvatar': LazyComponent<typeof import("../../app/components/ui/avatar/index")['Avatar']>
  'LazyAvatarFallback': LazyComponent<typeof import("../../app/components/ui/avatar/index")['AvatarFallback']>
  'LazyAvatarImage': LazyComponent<typeof import("../../app/components/ui/avatar/index")['AvatarImage']>
  'LazyAutoForm': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoForm']>
  'LazyAutoFormField': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormField']>
  'LazyAutoFormFieldArray': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldArray']>
  'LazyAutoFormFieldBoolean': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldBoolean']>
  'LazyAutoFormFieldDate': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldDate']>
  'LazyAutoFormFieldEnum': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldEnum']>
  'LazyAutoFormFieldFile': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldFile']>
  'LazyAutoFormFieldInput': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldInput']>
  'LazyAutoFormFieldNumber': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldNumber']>
  'LazyAutoFormFieldObject': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormFieldObject']>
  'LazyAutoFormLabel': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['AutoFormLabel']>
  'LazyConfig': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['Config']>
  'LazyConfigItem': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['ConfigItem']>
  'LazyFieldProps': LazyComponent<typeof import("../../app/components/ui/auto-form/index")['FieldProps']>
  'LazyBadge': LazyComponent<typeof import("../../app/components/ui/badge/index")['Badge']>
  'LazyBreadcrumb': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['Breadcrumb']>
  'LazyBreadcrumbEllipsis': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbEllipsis']>
  'LazyBreadcrumbItem': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbItem']>
  'LazyBreadcrumbLink': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbLink']>
  'LazyBreadcrumbList': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbList']>
  'LazyBreadcrumbPage': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbPage']>
  'LazyBreadcrumbSeparator': LazyComponent<typeof import("../../app/components/ui/breadcrumb/index")['BreadcrumbSeparator']>
  'LazyButton': LazyComponent<typeof import("../../app/components/ui/button/index")['Button']>
  'LazyButtonGroup': LazyComponent<typeof import("../../app/components/ui/button-group/index")['ButtonGroup']>
  'LazyButtonGroupSeparator': LazyComponent<typeof import("../../app/components/ui/button-group/index")['ButtonGroupSeparator']>
  'LazyButtonGroupText': LazyComponent<typeof import("../../app/components/ui/button-group/index")['ButtonGroupText']>
  'LazyCalendar': LazyComponent<typeof import("../../app/components/ui/calendar/index")['Calendar']>
  'LazyCalendarCell': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarCell']>
  'LazyCalendarCellTrigger': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarCellTrigger']>
  'LazyCalendarGrid': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGrid']>
  'LazyCalendarGridBody': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridBody']>
  'LazyCalendarGridHead': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridHead']>
  'LazyCalendarGridRow': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarGridRow']>
  'LazyCalendarHeadCell': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeadCell']>
  'LazyCalendarHeader': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeader']>
  'LazyCalendarHeading': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarHeading']>
  'LazyCalendarNextButton': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarNextButton']>
  'LazyCalendarPrevButton': LazyComponent<typeof import("../../app/components/ui/calendar/index")['CalendarPrevButton']>
  'LazyCard': LazyComponent<typeof import("../../app/components/ui/card/index")['Card']>
  'LazyCardAction': LazyComponent<typeof import("../../app/components/ui/card/index")['CardAction']>
  'LazyCardContent': LazyComponent<typeof import("../../app/components/ui/card/index")['CardContent']>
  'LazyCardDescription': LazyComponent<typeof import("../../app/components/ui/card/index")['CardDescription']>
  'LazyCardFooter': LazyComponent<typeof import("../../app/components/ui/card/index")['CardFooter']>
  'LazyCardHeader': LazyComponent<typeof import("../../app/components/ui/card/index")['CardHeader']>
  'LazyCardTitle': LazyComponent<typeof import("../../app/components/ui/card/index")['CardTitle']>
  'LazyCarousel': LazyComponent<typeof import("../../app/components/ui/carousel/index")['Carousel']>
  'LazyCarouselContent': LazyComponent<typeof import("../../app/components/ui/carousel/index")['CarouselContent']>
  'LazyCarouselItem': LazyComponent<typeof import("../../app/components/ui/carousel/index")['CarouselItem']>
  'LazyCarouselNext': LazyComponent<typeof import("../../app/components/ui/carousel/index")['CarouselNext']>
  'LazyCarouselPrevious': LazyComponent<typeof import("../../app/components/ui/carousel/index")['CarouselPrevious']>
  'LazyCarouselApi': LazyComponent<typeof import("../../app/components/ui/carousel/index")['CarouselApi']>
  'LazyAreaChart': LazyComponent<typeof import("../../app/components/ui/chart-area/index")['AreaChart']>
  'LazyBarChart': LazyComponent<typeof import("../../app/components/ui/chart-bar/index")['BarChart']>
  'LazyLineChart': LazyComponent<typeof import("../../app/components/ui/chart-line/index")['LineChart']>
  'LazyCommand': LazyComponent<typeof import("../../app/components/ui/command/index")['Command']>
  'LazyCommandDialog': LazyComponent<typeof import("../../app/components/ui/command/index")['CommandDialog']>
  'LazyCommandEmpty': LazyComponent<typeof import("../../app/components/ui/command/index")['CommandEmpty']>
  'LazyCommandGroup': LazyComponent<typeof import("../../app/components/ui/command/index")['CommandGroup']>
  'LazyCommandInput': LazyComponent<typeof import("../../app/components/ui/command/index")['CommandInput']>
  'LazyCommandItem': LazyComponent<typeof import("../../app/components/ui/command/index")['CommandItem']>
  'LazyCommandList': LazyComponent<typeof import("../../app/components/ui/command/index")['CommandList']>
  'LazyCommandSeparator': LazyComponent<typeof import("../../app/components/ui/command/index")['CommandSeparator']>
  'LazyCommandShortcut': LazyComponent<typeof import("../../app/components/ui/command/index")['CommandShortcut']>
  'LazyCheckbox': LazyComponent<typeof import("../../app/components/ui/checkbox/index")['Checkbox']>
  'LazyDonutChart': LazyComponent<typeof import("../../app/components/ui/chart-donut/index")['DonutChart']>
  'LazyChartCrosshair': LazyComponent<typeof import("../../app/components/ui/chart/index")['ChartCrosshair']>
  'LazyChartLegend': LazyComponent<typeof import("../../app/components/ui/chart/index")['ChartLegend']>
  'LazyChartSingleTooltip': LazyComponent<typeof import("../../app/components/ui/chart/index")['ChartSingleTooltip']>
  'LazyChartTooltip': LazyComponent<typeof import("../../app/components/ui/chart/index")['ChartTooltip']>
  'LazyCollapsible': LazyComponent<typeof import("../../app/components/ui/collapsible/index")['Collapsible']>
  'LazyCollapsibleContent': LazyComponent<typeof import("../../app/components/ui/collapsible/index")['CollapsibleContent']>
  'LazyCollapsibleTrigger': LazyComponent<typeof import("../../app/components/ui/collapsible/index")['CollapsibleTrigger']>
  'LazyField': LazyComponent<typeof import("../../app/components/ui/field/index")['Field']>
  'LazyFieldContent': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldContent']>
  'LazyFieldDescription': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldDescription']>
  'LazyFieldError': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldError']>
  'LazyFieldGroup': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldGroup']>
  'LazyFieldLabel': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldLabel']>
  'LazyFieldLegend': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldLegend']>
  'LazyFieldSeparator': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldSeparator']>
  'LazyFieldSet': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldSet']>
  'LazyFieldTitle': LazyComponent<typeof import("../../app/components/ui/field/index")['FieldTitle']>
  'LazyCombobox': LazyComponent<typeof import("../../app/components/ui/combobox/index")['Combobox']>
  'LazyComboboxAnchor': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxAnchor']>
  'LazyComboboxEmpty': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxEmpty']>
  'LazyComboboxGroup': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxGroup']>
  'LazyComboboxInput': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxInput']>
  'LazyComboboxItem': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxItem']>
  'LazyComboboxItemIndicator': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxItemIndicator']>
  'LazyComboboxList': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxList']>
  'LazyComboboxSeparator': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxSeparator']>
  'LazyComboboxViewport': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxViewport']>
  'LazyComboboxCancel': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxCancel']>
  'LazyComboboxTrigger': LazyComponent<typeof import("../../app/components/ui/combobox/index")['ComboboxTrigger']>
  'LazyDropdownMenu': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenu']>
  'LazyDropdownMenuCheckboxItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
  'LazyDropdownMenuContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
  'LazyDropdownMenuGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
  'LazyDropdownMenuItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
  'LazyDropdownMenuLabel': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
  'LazyDropdownMenuRadioGroup': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
  'LazyDropdownMenuRadioItem': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
  'LazyDropdownMenuSeparator': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
  'LazyDropdownMenuShortcut': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
  'LazyDropdownMenuSub': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
  'LazyDropdownMenuSubContent': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
  'LazyDropdownMenuSubTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
  'LazyDropdownMenuTrigger': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
  'LazyDropdownMenuPortal': LazyComponent<typeof import("../../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
  'LazyEmpty': LazyComponent<typeof import("../../app/components/ui/empty/index")['Empty']>
  'LazyEmptyContent': LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyContent']>
  'LazyEmptyDescription': LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyDescription']>
  'LazyEmptyHeader': LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyHeader']>
  'LazyEmptyMedia': LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyMedia']>
  'LazyEmptyTitle': LazyComponent<typeof import("../../app/components/ui/empty/index")['EmptyTitle']>
  'LazyHoverCard': LazyComponent<typeof import("../../app/components/ui/hover-card/index")['HoverCard']>
  'LazyHoverCardContent': LazyComponent<typeof import("../../app/components/ui/hover-card/index")['HoverCardContent']>
  'LazyHoverCardTrigger': LazyComponent<typeof import("../../app/components/ui/hover-card/index")['HoverCardTrigger']>
  'LazyContextMenu': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenu']>
  'LazyContextMenuCheckboxItem': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuCheckboxItem']>
  'LazyContextMenuContent': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuContent']>
  'LazyContextMenuGroup': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuGroup']>
  'LazyContextMenuItem': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuItem']>
  'LazyContextMenuLabel': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuLabel']>
  'LazyContextMenuRadioGroup': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuRadioGroup']>
  'LazyContextMenuRadioItem': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuRadioItem']>
  'LazyContextMenuSeparator': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuSeparator']>
  'LazyContextMenuShortcut': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuShortcut']>
  'LazyContextMenuSub': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuSub']>
  'LazyContextMenuSubContent': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuSubContent']>
  'LazyContextMenuSubTrigger': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuSubTrigger']>
  'LazyContextMenuTrigger': LazyComponent<typeof import("../../app/components/ui/context-menu/index")['ContextMenuTrigger']>
  'LazyInput': LazyComponent<typeof import("../../app/components/ui/input/index")['Input']>
  'LazyInputGroup': LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroup']>
  'LazyInputGroupAddon': LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupAddon']>
  'LazyInputGroupButton': LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupButton']>
  'LazyInputGroupInput': LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupInput']>
  'LazyInputGroupText': LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupText']>
  'LazyInputGroupTextarea': LazyComponent<typeof import("../../app/components/ui/input-group/index")['InputGroupTextarea']>
  'LazyInputOTP': LazyComponent<typeof import("../../app/components/ui/input-otp/index")['InputOTP']>
  'LazyInputOTPGroup': LazyComponent<typeof import("../../app/components/ui/input-otp/index")['InputOTPGroup']>
  'LazyInputOTPSeparator': LazyComponent<typeof import("../../app/components/ui/input-otp/index")['InputOTPSeparator']>
  'LazyInputOTPSlot': LazyComponent<typeof import("../../app/components/ui/input-otp/index")['InputOTPSlot']>
  'LazyDialog': LazyComponent<typeof import("../../app/components/ui/dialog/index")['Dialog']>
  'LazyDialogClose': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogClose']>
  'LazyDialogContent': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogContent']>
  'LazyDialogDescription': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogDescription']>
  'LazyDialogFooter': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogFooter']>
  'LazyDialogHeader': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogHeader']>
  'LazyDialogOverlay': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogOverlay']>
  'LazyDialogScrollContent': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogScrollContent']>
  'LazyDialogTitle': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogTitle']>
  'LazyDialogTrigger': LazyComponent<typeof import("../../app/components/ui/dialog/index")['DialogTrigger']>
  'LazyItem': LazyComponent<typeof import("../../app/components/ui/item/index")['Item']>
  'LazyItemActions': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemActions']>
  'LazyItemContent': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemContent']>
  'LazyItemDescription': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemDescription']>
  'LazyItemFooter': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemFooter']>
  'LazyItemGroup': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemGroup']>
  'LazyItemHeader': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemHeader']>
  'LazyItemMedia': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemMedia']>
  'LazyItemSeparator': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemSeparator']>
  'LazyItemTitle': LazyComponent<typeof import("../../app/components/ui/item/index")['ItemTitle']>
  'LazyLabel': LazyComponent<typeof import("../../app/components/ui/label/index")['Label']>
  'LazyDrawer': LazyComponent<typeof import("../../app/components/ui/drawer/index")['Drawer']>
  'LazyDrawerClose': LazyComponent<typeof import("../../app/components/ui/drawer/index")['DrawerClose']>
  'LazyDrawerContent': LazyComponent<typeof import("../../app/components/ui/drawer/index")['DrawerContent']>
  'LazyDrawerDescription': LazyComponent<typeof import("../../app/components/ui/drawer/index")['DrawerDescription']>
  'LazyDrawerFooter': LazyComponent<typeof import("../../app/components/ui/drawer/index")['DrawerFooter']>
  'LazyDrawerHeader': LazyComponent<typeof import("../../app/components/ui/drawer/index")['DrawerHeader']>
  'LazyDrawerOverlay': LazyComponent<typeof import("../../app/components/ui/drawer/index")['DrawerOverlay']>
  'LazyDrawerTitle': LazyComponent<typeof import("../../app/components/ui/drawer/index")['DrawerTitle']>
  'LazyDrawerTrigger': LazyComponent<typeof import("../../app/components/ui/drawer/index")['DrawerTrigger']>
  'LazyKbd': LazyComponent<typeof import("../../app/components/ui/kbd/index")['Kbd']>
  'LazyKbdGroup': LazyComponent<typeof import("../../app/components/ui/kbd/index")['KbdGroup']>
  'LazyFormControl': LazyComponent<typeof import("../../app/components/ui/form/index")['FormControl']>
  'LazyFormDescription': LazyComponent<typeof import("../../app/components/ui/form/index")['FormDescription']>
  'LazyFormItem': LazyComponent<typeof import("../../app/components/ui/form/index")['FormItem']>
  'LazyFormLabel': LazyComponent<typeof import("../../app/components/ui/form/index")['FormLabel']>
  'LazyFormMessage': LazyComponent<typeof import("../../app/components/ui/form/index")['FormMessage']>
  'LazyFORMITEMINJECTIONKEY': LazyComponent<typeof import("../../app/components/ui/form/index")['FORM_ITEM_INJECTION_KEY']>
  'LazyForm': LazyComponent<typeof import("../../app/components/ui/form/index")['Form']>
  'LazyFormField': LazyComponent<typeof import("../../app/components/ui/form/index")['FormField']>
  'LazyFormFieldArray': LazyComponent<typeof import("../../app/components/ui/form/index")['FormFieldArray']>
  'LazyNativeSelect': LazyComponent<typeof import("../../app/components/ui/native-select/index")['NativeSelect']>
  'LazyNativeSelectOptGroup': LazyComponent<typeof import("../../app/components/ui/native-select/index")['NativeSelectOptGroup']>
  'LazyNativeSelectOption': LazyComponent<typeof import("../../app/components/ui/native-select/index")['NativeSelectOption']>
  'LazyMenubar': LazyComponent<typeof import("../../app/components/ui/menubar/index")['Menubar']>
  'LazyMenubarCheckboxItem': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarCheckboxItem']>
  'LazyMenubarContent': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarContent']>
  'LazyMenubarGroup': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarGroup']>
  'LazyMenubarItem': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarItem']>
  'LazyMenubarLabel': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarLabel']>
  'LazyMenubarMenu': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarMenu']>
  'LazyMenubarRadioGroup': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarRadioGroup']>
  'LazyMenubarRadioItem': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarRadioItem']>
  'LazyMenubarSeparator': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarSeparator']>
  'LazyMenubarShortcut': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarShortcut']>
  'LazyMenubarSub': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarSub']>
  'LazyMenubarSubContent': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarSubContent']>
  'LazyMenubarSubTrigger': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarSubTrigger']>
  'LazyMenubarTrigger': LazyComponent<typeof import("../../app/components/ui/menubar/index")['MenubarTrigger']>
  'LazyNavigationMenu': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenu']>
  'LazyNavigationMenuContent': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuContent']>
  'LazyNavigationMenuIndicator': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuIndicator']>
  'LazyNavigationMenuItem': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuItem']>
  'LazyNavigationMenuLink': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuLink']>
  'LazyNavigationMenuList': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuList']>
  'LazyNavigationMenuTrigger': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuTrigger']>
  'LazyNavigationMenuViewport': LazyComponent<typeof import("../../app/components/ui/navigation-menu/index")['NavigationMenuViewport']>
  'LazyNumberField': LazyComponent<typeof import("../../app/components/ui/number-field/index")['NumberField']>
  'LazyNumberFieldContent': LazyComponent<typeof import("../../app/components/ui/number-field/index")['NumberFieldContent']>
  'LazyNumberFieldDecrement': LazyComponent<typeof import("../../app/components/ui/number-field/index")['NumberFieldDecrement']>
  'LazyNumberFieldIncrement': LazyComponent<typeof import("../../app/components/ui/number-field/index")['NumberFieldIncrement']>
  'LazyNumberFieldInput': LazyComponent<typeof import("../../app/components/ui/number-field/index")['NumberFieldInput']>
  'LazyPinInput': LazyComponent<typeof import("../../app/components/ui/pin-input/index")['PinInput']>
  'LazyPinInputGroup': LazyComponent<typeof import("../../app/components/ui/pin-input/index")['PinInputGroup']>
  'LazyPinInputSeparator': LazyComponent<typeof import("../../app/components/ui/pin-input/index")['PinInputSeparator']>
  'LazyPinInputSlot': LazyComponent<typeof import("../../app/components/ui/pin-input/index")['PinInputSlot']>
  'LazyPagination': LazyComponent<typeof import("../../app/components/ui/pagination/index")['Pagination']>
  'LazyPaginationContent': LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationContent']>
  'LazyPaginationEllipsis': LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationEllipsis']>
  'LazyPaginationFirst': LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationFirst']>
  'LazyPaginationItem': LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationItem']>
  'LazyPaginationLast': LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationLast']>
  'LazyPaginationNext': LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationNext']>
  'LazyPaginationPrevious': LazyComponent<typeof import("../../app/components/ui/pagination/index")['PaginationPrevious']>
  'LazyProgress': LazyComponent<typeof import("../../app/components/ui/progress/index")['Progress']>
  'LazyRadioGroup': LazyComponent<typeof import("../../app/components/ui/radio-group/index")['RadioGroup']>
  'LazyRadioGroupItem': LazyComponent<typeof import("../../app/components/ui/radio-group/index")['RadioGroupItem']>
  'LazyPopover': LazyComponent<typeof import("../../app/components/ui/popover/index")['Popover']>
  'LazyPopoverAnchor': LazyComponent<typeof import("../../app/components/ui/popover/index")['PopoverAnchor']>
  'LazyPopoverContent': LazyComponent<typeof import("../../app/components/ui/popover/index")['PopoverContent']>
  'LazyPopoverTrigger': LazyComponent<typeof import("../../app/components/ui/popover/index")['PopoverTrigger']>
  'LazyResizableHandle': LazyComponent<typeof import("../../app/components/ui/resizable/index")['ResizableHandle']>
  'LazyResizablePanel': LazyComponent<typeof import("../../app/components/ui/resizable/index")['ResizablePanel']>
  'LazyResizablePanelGroup': LazyComponent<typeof import("../../app/components/ui/resizable/index")['ResizablePanelGroup']>
  'LazyScrollArea': LazyComponent<typeof import("../../app/components/ui/scroll-area/index")['ScrollArea']>
  'LazyScrollBar': LazyComponent<typeof import("../../app/components/ui/scroll-area/index")['ScrollBar']>
  'LazyRangeCalendar': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendar']>
  'LazyRangeCalendarCell': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarCell']>
  'LazyRangeCalendarCellTrigger': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarCellTrigger']>
  'LazyRangeCalendarGrid': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGrid']>
  'LazyRangeCalendarGridBody': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridBody']>
  'LazyRangeCalendarGridHead': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridHead']>
  'LazyRangeCalendarGridRow': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarGridRow']>
  'LazyRangeCalendarHeadCell': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeadCell']>
  'LazyRangeCalendarHeader': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeader']>
  'LazyRangeCalendarHeading': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarHeading']>
  'LazyRangeCalendarNextButton': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarNextButton']>
  'LazyRangeCalendarPrevButton': LazyComponent<typeof import("../../app/components/ui/range-calendar/index")['RangeCalendarPrevButton']>
  'LazySeparator': LazyComponent<typeof import("../../app/components/ui/separator/index")['Separator']>
  'LazySheet': LazyComponent<typeof import("../../app/components/ui/sheet/index")['Sheet']>
  'LazySheetClose': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetClose']>
  'LazySheetContent': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetContent']>
  'LazySheetDescription': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetDescription']>
  'LazySheetFooter': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetFooter']>
  'LazySheetHeader': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetHeader']>
  'LazySheetTitle': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTitle']>
  'LazySheetTrigger': LazyComponent<typeof import("../../app/components/ui/sheet/index")['SheetTrigger']>
  'LazyToaster': LazyComponent<typeof import("../../app/components/ui/sonner/index")['Toaster']>
  'LazySkeleton': LazyComponent<typeof import("../../app/components/ui/skeleton/index")['Skeleton']>
  'LazySidebar': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['Sidebar']>
  'LazySidebarContent': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarContent']>
  'LazySidebarFooter': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarFooter']>
  'LazySidebarGroup': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroup']>
  'LazySidebarGroupAction': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupAction']>
  'LazySidebarGroupContent': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupContent']>
  'LazySidebarGroupLabel': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarGroupLabel']>
  'LazySidebarHeader': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarHeader']>
  'LazySidebarInput': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInput']>
  'LazySidebarInset': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarInset']>
  'LazySidebarMenu': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenu']>
  'LazySidebarMenuAction': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuAction']>
  'LazySidebarMenuBadge': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuBadge']>
  'LazySidebarMenuButton': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuButton']>
  'LazySidebarMenuItem': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuItem']>
  'LazySidebarMenuSkeleton': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSkeleton']>
  'LazySidebarMenuSub': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSub']>
  'LazySidebarMenuSubButton': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubButton']>
  'LazySidebarMenuSubItem': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarMenuSubItem']>
  'LazySidebarProvider': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarProvider']>
  'LazySidebarRail': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarRail']>
  'LazySidebarSeparator': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarSeparator']>
  'LazySidebarTrigger': LazyComponent<typeof import("../../app/components/ui/sidebar/index")['SidebarTrigger']>
  'LazySelect': LazyComponent<typeof import("../../app/components/ui/select/index")['Select']>
  'LazySelectContent': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectContent']>
  'LazySelectGroup': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectGroup']>
  'LazySelectItem': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItem']>
  'LazySelectItemText': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectItemText']>
  'LazySelectLabel': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectLabel']>
  'LazySelectScrollDownButton': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollDownButton']>
  'LazySelectScrollUpButton': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectScrollUpButton']>
  'LazySelectSeparator': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectSeparator']>
  'LazySelectTrigger': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectTrigger']>
  'LazySelectValue': LazyComponent<typeof import("../../app/components/ui/select/index")['SelectValue']>
  'LazySlider': LazyComponent<typeof import("../../app/components/ui/slider/index")['Slider']>
  'LazySpinner': LazyComponent<typeof import("../../app/components/ui/spinner/index")['Spinner']>
  'LazyTable': LazyComponent<typeof import("../../app/components/ui/table/index")['Table']>
  'LazyTableBody': LazyComponent<typeof import("../../app/components/ui/table/index")['TableBody']>
  'LazyTableCaption': LazyComponent<typeof import("../../app/components/ui/table/index")['TableCaption']>
  'LazyTableCell': LazyComponent<typeof import("../../app/components/ui/table/index")['TableCell']>
  'LazyTableEmpty': LazyComponent<typeof import("../../app/components/ui/table/index")['TableEmpty']>
  'LazyTableFooter': LazyComponent<typeof import("../../app/components/ui/table/index")['TableFooter']>
  'LazyTableHead': LazyComponent<typeof import("../../app/components/ui/table/index")['TableHead']>
  'LazyTableHeader': LazyComponent<typeof import("../../app/components/ui/table/index")['TableHeader']>
  'LazyTableRow': LazyComponent<typeof import("../../app/components/ui/table/index")['TableRow']>
  'LazyTabs': LazyComponent<typeof import("../../app/components/ui/tabs/index")['Tabs']>
  'LazyTabsContent': LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsContent']>
  'LazyTabsList': LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsList']>
  'LazyTabsTrigger': LazyComponent<typeof import("../../app/components/ui/tabs/index")['TabsTrigger']>
  'LazySwitch': LazyComponent<typeof import("../../app/components/ui/switch/index")['Switch']>
  'LazyStepper': LazyComponent<typeof import("../../app/components/ui/stepper/index")['Stepper']>
  'LazyStepperDescription': LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperDescription']>
  'LazyStepperIndicator': LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperIndicator']>
  'LazyStepperItem': LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperItem']>
  'LazyStepperSeparator': LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperSeparator']>
  'LazyStepperTitle': LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperTitle']>
  'LazyStepperTrigger': LazyComponent<typeof import("../../app/components/ui/stepper/index")['StepperTrigger']>
  'LazyTagsInput': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInput']>
  'LazyTagsInputInput': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInputInput']>
  'LazyTagsInputItem': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInputItem']>
  'LazyTagsInputItemDelete': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInputItemDelete']>
  'LazyTagsInputItemText': LazyComponent<typeof import("../../app/components/ui/tags-input/index")['TagsInputItemText']>
  'LazyTextarea': LazyComponent<typeof import("../../app/components/ui/textarea/index")['Textarea']>
  'LazyToggleGroup': LazyComponent<typeof import("../../app/components/ui/toggle-group/index")['ToggleGroup']>
  'LazyToggleGroupItem': LazyComponent<typeof import("../../app/components/ui/toggle-group/index")['ToggleGroupItem']>
  'LazyToggle': LazyComponent<typeof import("../../app/components/ui/toggle/index")['Toggle']>
  'LazyTooltip': LazyComponent<typeof import("../../app/components/ui/tooltip/index")['Tooltip']>
  'LazyTooltipContent': LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipContent']>
  'LazyTooltipProvider': LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipProvider']>
  'LazyTooltipTrigger': LazyComponent<typeof import("../../app/components/ui/tooltip/index")['TooltipTrigger']>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
